// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_DOS.Data;

namespace Projeto_DOS.Migrations
{
    [DbContext(typeof(Projeto_DOSContext))]
    partial class Projeto_DOSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Projeto_DOS.Models.Cadalu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apelido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodAlu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCuR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Crea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Curri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataInc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmDia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fpag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Histo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NFicha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoCIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turma")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Cadalu");
                });
#pragma warning restore 612, 618
        }
    }
}
